---
name: Erlang CI

"on": [push, workflow_dispatch]

jobs:
  vsns:
    runs-on: ubuntu-22.04
    outputs:
      # renovate datasource: github-runners, depName: ubuntu
      ubuntu: 22.04
      # renovate datasource: github-runners, depName: windows
      windows: 2022
      # renovate datasource: github-runners, depName: macos
      macos: 14
      # renovate datasource: github-tags, depName: erlang/rebar3
      rebar3: 3.22.1

    steps:
      - run: echo "versions set!"

  ci:
    name: Erlang CI
    needs: [vsns]

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-base: ubuntu
            os-vsn: ${{ needs.vsns.outputs.ubuntu }}
            otp-version: 25
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}
          - os-base: ubuntu
            os-vsn: ${{ needs.vsns.outputs.ubuntu }}
            otp-version: 26
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}
          - os-base: windows
            os-vsn: ${{ needs.vsns.outputs.windows }}
            otp-version: 25
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}
          - os-base: windows
            os-vsn: ${{ needs.vsns.outputs.windows }}
            otp-version: 26
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}
          # macos, for now, is considered best-effort
          - os-base: macos
            os-vsn: ${{ needs.vsns.outputs.macos }}
            otp-version: 25
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}
          - os-base: macos  # macos, for now, is considered best-effort
            os-vsn: ${{ needs.vsns.outputs.macos }}
            otp-version: 26
            rebar3-version: ${{ needs.vsns.outputs.rebar3 }}

    runs-on: ${{matrix.os-base}}-${{matrix.os-vsn}}

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: erlef/setup-beam@0a541161e47ec43ccbd9510053c5f336ca76c2a2 # v1.17.6
        id: setup-beam
        with:
          otp-version: ${{matrix.otp-version}}
          rebar3-version: ${{matrix.rebar3-version}}
        if: ${{matrix.os-base != 'macos'}}

      - run: |
          brew install erlang@${{matrix.otp-version}}
          brew install rebar3
        if: ${{matrix.os-base == 'macos'}}

      - name: Restore _build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
        if: ${{matrix.os-base != 'macos'}}

      - name: Restore rebar3's cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
        if: ${{matrix.os-base != 'macos'}}

      - name: Check file format
        run: rebar3 fmt --check
        if: ${{matrix.os-base != 'windows'}}

      - name: Continuous Integration
        run: rebar3 as test ci
