---
name: Erlang CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  vsns:
    runs-on: ubuntu-22.04
    outputs:
      # renovate datasource: github-runners, depName: ubuntu
      ubuntu: 22.04
      # renovate datasource: github-runners, depName: windows
      windows: 2022
      # renovate datasource: github-runners, depName: macos
      macos: 14

    steps:
      - run: echo "versions set!"

  ci:
    name: Erlang CI
    needs: [vsns]

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-base: ubuntu
            os-vsn: ${{ needs.vsns.outputs.ubuntu }}
          - os-base: windows
            os-vsn: ${{ needs.vsns.outputs.windows }}
          - os-base: macos  # macos, for now, is considered best-effort
            os-vsn: ${{ needs.vsns.outputs.macos }}

    runs-on: ${{matrix.os-base}}-${{matrix.os-vsn}}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        id: setup-beam
        with:
          version-type: strict
          version-file: .tool-versions
        if: ${{matrix.os-base != 'macos'}}

      - run: |
          # there be dragons
          erlang=$(< .tool-versions grep erlang | sed -E 's/erlang ([^\.]+).*/\1/g')
          brew install "erlang@${erlang}"
        if: ${{matrix.os-base == 'macos'}}

      - name: Restore _build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
        if: ${{matrix.os-base != 'macos'}}

      - name: Restore rebar3's cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"
        if: ${{matrix.os-base != 'macos'}}

      - name: Check file format
        run: rebar3 fmt --check
        if: ${{matrix.os-base != 'windows'}}

      - name: Continuous Integration
        run: rebar3 as test ci
