---
name: Erlang CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  vsns:
    runs-on: ubuntu-24.04
    outputs:
      # renovate datasource: github-runners, depName: ubuntu
      ubuntu: 24.04
      # renovate datasource: github-runners, depName: windows
      windows: 2022
      # renovate datasource: github-runners, depName: macos
      macos: 15

    steps:
      - run: echo "versions set!"

  ci:
    name: Erlang CI
    needs: [vsns]

    strategy:
      fail-fast: false
      matrix:
        include:
          - os-base: ubuntu
            os-vsn: ${{ needs.vsns.outputs.ubuntu }}
          - os-base: windows
            os-vsn: ${{ needs.vsns.outputs.windows }}
          - os-base: macos
            os-vsn: ${{ needs.vsns.outputs.macos }}

    runs-on: ${{matrix.os-base}}-${{matrix.os-vsn}}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        id: setup-beam
        with:
          version-type: strict
          version-file: .tool-versions

      - name: Restore _build
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: _build
          key: "_build-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"

      - name: Restore rebar3's cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/rebar3
          key: "rebar3-cache-for\
                -os-${{runner.os}}\
                -otp-${{steps.setup-beam.outputs.otp-version}}\
                -rebar3-${{steps.setup-beam.outputs.rebar3-version}}\
                -hash-${{hashFiles('rebar.lock')}}"

      - name: Check file format
        run: rebar3 fmt --check
        if: ${{matrix.os-base != 'windows'}}

      - name: Continuous Integration
        run: rebar3 as test ci
