---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: |
            .github/**/*.md
            *.md
            LICENSE

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: |
            .github/**/*.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml

      - name: actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72
        env:
          SHELLCHECK_OPTS: -o all
