---
name: Lint

"on": [push, workflow_dispatch]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.6

      # uses .markdownlint.yml for configuration
      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16.0.0
        with:
          globs: |
            .github/**/*.md
            *.md
            LICENSE

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: |
            .github/**/*.yml
            .*.yml
          strict: true
          config_file: .yamllint.yml

      - name: actionlint
        uses: reviewdog/action-actionlint@v1.48.0
        env:
          SHELLCHECK_OPTS: -o all
