---
name: Update dependencies

"on":
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          rebar3-version: 3
      - run: ./.github/workflows/rebar3_depup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
